package application;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.imageio.ImageIO;

import javafx.embed.swing.SwingFXUtils;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.image.Image;
import javafx.scene.image.WritableImage;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;

public class GamePlayController implements Initializable{
	
	@FXML
	private Canvas canvas1;
	@FXML
	private Canvas canvas2;
	
	public int width;
	public int height;
	
	GraphicsContext gc1,gc2;
	Image BACKGROUND;
	Image background2;
	Image Click;
	Image SetIcon;
	private WritableImage wImage;
	private File file= new File("res/white.png");
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		width=(int) canvas1.getWidth();
		height=(int) canvas1.getHeight();
		//canvas2=new Canvas(canvas.getWidth(),canvas.getHeight());
		wImage=new WritableImage(width,height);
		
		gc1 = canvas1.getGraphicsContext2D();
		gc1.setStroke(Color.RED);
        gc1.setLineWidth(5);
        
        gc2 = canvas2.getGraphicsContext2D();
		gc2.setStroke(Color.RED);
        gc2.setLineWidth(5);
        
        Matrix.setUpMatrix();
        
 
        
        try {
			BACKGROUND=new Image(new FileInputStream("res/Wizard_Castle.jpg"));
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
   
      
        
        gc1.drawImage(BACKGROUND, 1, 0);
     
      
		
	}
	
	@FXML
	public void onMouseDragged(MouseEvent event) {
		// TODO Autogenerated
		
		gc1.lineTo(event.getX(), event.getY());
		gc1.stroke();
		
		gc2.lineTo(event.getX(), event.getY());
		gc2.stroke();
		
		if((int)event.getX()>20 && (int)event.getX()<width-20 && (int)event.getY()>20 && (int)event.getY()<height-20 ) {
			Matrix.fillOne((int)event.getY(), (int)event.getX());
		}
		
		
//		System.out.println(event.getX());
//		System.out.println(event.getY());
		
	}
	
	@FXML
	public void onMousePressed(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("press");
		
		
		gc1.beginPath();
		gc1.moveTo(event.getX(), event.getY());
		gc1.stroke();
	
		
		gc2.beginPath();
		gc2.moveTo(event.getX(), event.getY());
		gc2.stroke();
		
		gc1.drawImage(BACKGROUND, 0, 0);
	}
	
	@FXML
	public void onMouseReleased(MouseEvent event) {
		// TODO Autogenerated
		
		canvas2.snapshot(null, wImage);
		try {
			ImageIO.write(SwingFXUtils.fromFXImage(wImage,null), "png", file);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		Matrix.resizeMatrix();
		Matrix.display();
		Matrix.setUpMatrix();
		
		System.out.println("release");
		gc1.drawImage(BACKGROUND, 0, 0);
		gc2.clearRect(0, 0, canvas2.getWidth(), canvas2.getHeight());
		
	}

}
