package application;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javax.imageio.ImageIO;

import javafx.embed.swing.SwingFXUtils;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.image.Image;
import javafx.scene.image.WritableImage;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;

public class MagicFXController implements Initializable{
	
	@FXML
	private Canvas canvas;
	
	private Canvas canvas2;
	public int width;
	public int height;
	
	GraphicsContext gc1,gc2;
	Image BACKGROUND;
	private WritableImage wImage;
	private File file= new File("res/white.png");
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		width=(int) canvas.getWidth();
		height=(int) canvas.getHeight();
		canvas2=new Canvas(canvas.getWidth(),canvas.getHeight());
		wImage=new WritableImage(width,height);
		gc1 = canvas.getGraphicsContext2D();
		gc1.setStroke(Color.RED);
        gc1.setLineWidth(10);
        
        gc2 = canvas2.getGraphicsContext2D();
		gc2.setStroke(Color.RED);
        gc2.setLineWidth(10);
        
        try {
			BACKGROUND=new Image(new FileInputStream("res/Wizard_Castle.jpg"));
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
        gc1.drawImage(BACKGROUND, 0, 0);
		
	}
	
	@FXML
	public void onMouseDragged(MouseEvent event) {
		// TODO Autogenerated
		gc1.lineTo(event.getX(), event.getY());
		gc1.stroke();
		gc2.lineTo(event.getX(), event.getY());
		gc2.stroke();
		
		System.out.println("drag");
	}
	
	@FXML
	public void onMousePressed(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("press");
		gc1.beginPath();
		gc1.moveTo(event.getX(), event.getY());
		gc1.stroke();
		
		gc2.beginPath();
		gc2.moveTo(event.getX(), event.getY());
		gc2.stroke();
	}
	
	@FXML
	public void onMouseReleased(MouseEvent event) {
		// TODO Autogenerated
		
		canvas2.snapshot(null, wImage);
		try {
			ImageIO.write(SwingFXUtils.fromFXImage(wImage,null), "png", file);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		System.out.println("release");
		gc1.drawImage(BACKGROUND, 0, 0);
		gc2.clearRect(0, 0, canvas2.getWidth(), canvas2.getHeight());
		
	}

}
